name: format

on:
  push:
    branches-ignore:
      - production
  pull_request:
    branches-ignore:
      - production
  workflow_dispatch:
  workflow_run:
    workflows: ["sdk"]
    types:
      - completed
jobs:
  format:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: run
        run: |
          ./script/format.ts
        env:
          CI: true
          PUSH_BRANCH: ${{ github.event.pull_request.head.ref || github.ref_name }}
